# Generated by Django 2.1.7 on 2019-03-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offer_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_canceled',
            field=models.NullBooleanField(verbose_name='Abgebrochen'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_finished',
            field=models.NullBooleanField(verbose_name='Abgeschloßen'),
        ),
    ]
