# Generated by Django 2.1.7 on 2019-03-27 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('offer', '0003_auto_20190327_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.NullBooleanField(verbose_name='Administrator')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member', verbose_name='Mitglied')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.Offer', verbose_name='Angebots')),
            ],
        ),
    ]
