# Generated by Django 2.1.7 on 2019-03-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('offer', '0004_memberoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='members',
            field=models.ManyToManyField(related_name='offers', through='offer.MemberOffer', to='member.Member'),
        ),
    ]
