# Generated by Django 2.1.7 on 2019-03-27 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_offer_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberoffer',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.Offer', verbose_name='Angebot'),
        ),
    ]
