# Generated by Django 2.1.7 on 2019-03-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_auto_20190327_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberoffer',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membersoffers', to='member.Member', verbose_name='Mitglied'),
        ),
        migrations.AlterField(
            model_name='memberoffer',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membersoffers', to='offer.Offer', verbose_name='Angebot'),
        ),
    ]
