# Generated by Django 2.1.7 on 2019-03-27 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0006_auto_20190327_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_from', models.DateTimeField(blank=True, null=True, verbose_name='Zeitpunkt von')),
                ('datetime_to', models.DateTimeField(blank=True, null=True, verbose_name='Zeitpunkt bis')),
                ('member_offer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.MemberOffer')),
            ],
        ),
    ]
