# Generated by Django 2.1.7 on 2019-03-27 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0002_auto_20190327_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='member_offer_id',
            new_name='member_offer',
        ),
    ]
