# Generated by Django 2.1.7 on 2019-03-31 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0003_auto_20190327_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='datetime_from',
            field=models.DateTimeField(null=True, verbose_name='Zeitpunkt von'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='datetime_to',
            field=models.DateTimeField(null=True, verbose_name='Zeitpunkt bis'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='member_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='offer.MemberOffer'),
        ),
    ]
