# Generated by Django 2.1.7 on 2019-04-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0004_auto_20190331_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.NullBooleanField(verbose_name='Zustimmung')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suggestion.Suggestion', verbose_name='Terminvorschlag')),
            ],
        ),
    ]
