# Generated by Django 2.1.7 on 2019-04-01 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('suggestion', '0005_membersuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.NullBooleanField(verbose_name='Zustimmung')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='member.Member')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='suggestion.Suggestion', verbose_name='Terminvorschlag')),
            ],
        ),
        migrations.RemoveField(
            model_name='membersuggestion',
            name='suggestion',
        ),
        migrations.DeleteModel(
            name='MemberSuggestion',
        ),
    ]
