# Generated by Django 2.1.7 on 2019-04-02 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_auto_20190331_1800'),
        ('suggestion', '0007_auto_20190401_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.Offer', verbose_name='Angebot'),
        ),
    ]
